version: '3.4'

volumes:
  chaindata:

secrets:
  eth_keyfile:
    external: true

services:

  geth:
    image: geth:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - chaindata:/root/.ethereum/geth 
      - type: bind
        source: /tmp/ipc
        target: /tmp/ipc
    secrets:
      - eth_keyfile

