version: '3.4'

volumes:
  chaindata:

secrets:
  eth_keyfile:
    external: true

services:

  server:
    image: ethnode_server:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - chaindata:${HOME}/.ethereum/geth
      - type: bind
        source: /tmp/ipc
        target: /tmp/ipc
    secrets:
      - eth_keyfile
