#!/bin/bash
set -e

provider='geth'

script="`pwd`/$1"

v=latest # tweak to deploy a specific version number
me=`whoami` # your docker.io username
image="$me/ethprovider_$provider:$v"

if [[ -f "$script" ]]
then
  echo "Bind mounting $script"
  bind="-v $script:/root/$1"
  docker run -it -v ethprovider_ipc:/tmp/ipc $bind $image attach /tmp/ipc/$provider.ipc --preload /root/$1
else
  docker run -it -v ethprovider_ipc:/tmp/ipc $image attach /tmp/ipc/$provider.ipc
fi

